<form action="??" method="post">
    来访日期<input type="text" name="fdata"><br />
    来访时间<input type="text" name="ftime"><br />
    访客姓名<input type="text" name="fname"><br />
    来访人数<input type="text" name="fnum"><br />
    访客电话<input type="text" name="ftel"><br />
    来访地区<input type="text" name="farea"><br />
    来访楼层<input type="text" name="ffloor"><br />
    来访事理<input type="text" name="fmemo"><br />
    <input type="hidden" value="1" name="status">
    <input type="submit" value="预约"><input type="reset" value="重填">
</form>