<html>
<head>
    <meta charset="utf-8">
</head>
<body>
<form  action="http://www.wangjinghai.com/yafnew/index.php/index/User/add" method="post">
    <table>
        <tr><th>来访日期</th><td><input type="text" name="fdata"></td></tr>
        <tr><th>来访时间</th><td><input type="text" name="ftime"></td></tr>
        <tr><th>访客姓名</th><td><input type="text" name="fname"></td></tr>
        <tr><th>来访人数</th><td><input type="text" name="fnum"></td></tr>
        <tr><th>访客电话</th><td><input type="text" name="ftel"></td></tr>
        <tr><th>来访地区</th><td><input type="text" name="farea"></td></tr>
        <tr><th>来访楼层</th><td><input type="text" name="ffloor"></td></tr>
        <tr><th>来访事理</th><td><input type="text" name="fmemo"></td></tr>
        <tr><td colspan=2><input type="hidden" value="1" name="status">
                &nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" value="预约">&nbsp;&nbsp;&nbsp;<input
                    type="reset" value="重填"></td></tr>
    </table>
</form>
</body>
</html>